/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwaggerRouteImport } from './routes/swagger'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGenerateHhwRouteImport } from './routes/api/public/generate-hhw'
import { Route as ApiPublicGenerateExamRouteImport } from './routes/api/public/generate-exam'

const SwaggerRoute = SwaggerRouteImport.update({
  id: '/swagger',
  path: '/swagger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateHhwRoute = ApiPublicGenerateHhwRouteImport.update({
  id: '/api/public/generate-hhw',
  path: '/api/public/generate-hhw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateExamRoute = ApiPublicGenerateExamRouteImport.update({
  id: '/api/public/generate-exam',
  path: '/api/public/generate-exam',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/swagger': typeof SwaggerRoute
  '/api/public/generate-exam': typeof ApiPublicGenerateExamRoute
  '/api/public/generate-hhw': typeof ApiPublicGenerateHhwRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/swagger': typeof SwaggerRoute
  '/api/public/generate-exam': typeof ApiPublicGenerateExamRoute
  '/api/public/generate-hhw': typeof ApiPublicGenerateHhwRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/swagger': typeof SwaggerRoute
  '/api/public/generate-exam': typeof ApiPublicGenerateExamRoute
  '/api/public/generate-hhw': typeof ApiPublicGenerateHhwRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/swagger'
    | '/api/public/generate-exam'
    | '/api/public/generate-hhw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/swagger'
    | '/api/public/generate-exam'
    | '/api/public/generate-hhw'
  id:
    | '__root__'
    | '/'
    | '/swagger'
    | '/api/public/generate-exam'
    | '/api/public/generate-hhw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SwaggerRoute: typeof SwaggerRoute
  ApiPublicGenerateExamRoute: typeof ApiPublicGenerateExamRoute
  ApiPublicGenerateHhwRoute: typeof ApiPublicGenerateHhwRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swagger': {
      id: '/swagger'
      path: '/swagger'
      fullPath: '/swagger'
      preLoaderRoute: typeof SwaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-hhw': {
      id: '/api/public/generate-hhw'
      path: '/api/public/generate-hhw'
      fullPath: '/api/public/generate-hhw'
      preLoaderRoute: typeof ApiPublicGenerateHhwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-exam': {
      id: '/api/public/generate-exam'
      path: '/api/public/generate-exam'
      fullPath: '/api/public/generate-exam'
      preLoaderRoute: typeof ApiPublicGenerateExamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SwaggerRoute: SwaggerRoute,
  ApiPublicGenerateExamRoute: ApiPublicGenerateExamRoute,
  ApiPublicGenerateHhwRoute: ApiPublicGenerateHhwRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
